from setuptools import setup
setup(name='scoobe',
      version='0.1.0.dev1',
      description='commands for manipulating a device through oobe',
      url='https://github.com/mattrixman/scoobe',
      author='Matt Rixman',
      author_email='matt.rixman@clover.com',
      packages=['scoobe'],
      python_requires= '>=3',
      install_requires=['uiautomator', 'sh', 'mysqlclient', 'sshconf', 'requests'],
      entry_points={'console_scripts' : ['press_button = scoobe.button:press',
                                         'device_info = scoobe.device:info',
                                         'wait_ready = scoobe.device:wait_ready',
                                         'target_device = scoobe.device:set_target',
                                         'device_serial = scoobe.device:get_serial',
                                         'device_cpuid = scoobe.device:get_cpuid',
                                         'device_merchant = scoobe.server:print_merchant',
                                         'get_merchant_id = scoobe.server:print_merchant_id',
                                         'deprovision_device = scoobe.server:deprovision',
                                         'provision_device = scoobe.server:provision',
                                         'unaccept_terms= scoobe.server:unaccept',
                                         'accept_terms= scoobe.server:accept',
                                         'activation_code = scoobe.server:print_activation_code'] }
      )

